<a href="https://colab.research.google.com/github/msingh-0007/Shape_Generator/blob/main/Manjit_HW4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports and pip installations (if needed)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn import svm
from sklearn import datasets
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Perceptron
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.neighbors import KNeighborsClassifier

# Load the dataset (load remotely, not locally)

# Output the first 15 rows of the data
# Display a summary of the table information (number of datapoints, etc.)

In [ ]:
Iris = pd.read_csv("https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv")
Iris.head(15)

sepal.length  sepal.width  petal.length  petal.width variety
0            5.1          3.5           1.4          0.2  Setosa
1            4.9          3.0           1.4          0.2  Setosa
2            4.7          3.2           1.3          0.2  Setosa
3            4.6          3.1           1.5          0.2  Setosa
4            5.0          3.6           1.4          0.2  Setosa
5            5.4          3.9           1.7          0.4  Setosa
6            4.6          3.4           1.4          0.3  Setosa
7            5.0          3.4           1.5          0.2  Setosa
8            4.4          2.9           1.4          0.2  Setosa
9            4.9          3.1           1.5          0.1  Setosa
10           5.4          3.7           1.5          0.2  Setosa
11           4.8          3.4           1.6          0.2  Setosa
12           4.8          3.0           1.4          0.1  Setosa
13           4.3          3.0           1.1          0.1  Setosa
14           5.8          4.0           1.2          0.2  Setosa

First 15 of the Iris Dataset from the github site

In [ ]:
Iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


Summary of the Iris Dataset

# Take the dataset and split it into our features (X) and label (y)

# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)

In [ ]:
X = Iris[["sepal.length","sepal.width","petal.length","petal.width"]]
y = Iris["variety"]
X_train, X_test, Y_train, Y_test=train_test_split(X,y,test_size=0.1,train_size=0.9)

Test Split 90% Training, 10% Testing

# i. Use sklearn to train a LogisticRegression model on the training set

# ii. For a sample datapoint, predict the probabilities for each possible class

# iii. Report on the score for Logistic regression model, what does the score measure?

# iv. Extract the coefficents and intercepts for the boundary line(s)

In [ ]:
clf = LogisticRegression(random_state=0, max_iter = 200).fit(X_train,Y_train)
                                            

In [ ]:
X_test

sepal.length  sepal.width  petal.length  petal.width
58            6.6          2.9           4.6          1.3
37            4.9          3.6           1.4          0.1
111           6.4          2.7           5.3          1.9
105           7.6          3.0           6.6          2.1
40            5.0          3.5           1.3          0.3
4             5.0          3.6           1.4          0.2
67            5.8          2.7           4.1          1.0
56            6.3          3.3           4.7          1.6
49            5.0          3.3           1.4          0.2
79            5.7          2.6           3.5          1.0
73            6.1          2.8           4.7          1.2
127           6.1          3.0           4.9          1.8
96            5.7          2.9           4.2          1.3
15            5.7          4.4           1.5          0.4
68            6.2          2.2           4.5          1.5

Training LogisticRegression Model, and using the Top test value as our sample datapoint

In [ ]:
clf.classes_

array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

Showing how the classes are arranged, and then their associated probabilities

In [ ]:
clf.predict_proba(X_test.head(1))

array([[0.00334818, 0.88016954, 0.11648227]])

In [ ]:
scores = cross_val_score(clf, X, y, cv=5)
scores.mean()

0.9733333333333334

The Score Measures the accuracy of the Logistic Regression function, though for some odd reason the accuracy is 100% when using x_test y_test, so I had to use Cross-validation

In [ ]:
clf.intercept_

array([  9.48389919,   2.18275381, -11.666653  ])

In [ ]:
clf.coef_

array([[-0.39437478,  0.93734093, -2.44717233, -1.0635851 ],
       [ 0.47671034, -0.28359102, -0.18593408, -0.86151856],
       [-0.08233556, -0.6537499 ,  2.63310641,  1.92510365]])

Intercept and Coefficient values

In [ ]:
clf.densify()

LogisticRegression(max_iter=200, random_state=0)

# i. Use sklearn to train a Support Vector Classifier on the training set

# ii. For a sample datapoint, predict the probabilities for each possible class

# iii. Report on the score for the SVM, what does the score measure?

In [ ]:
clf = svm.SVC(probability = True)
clf.fit(X_train, Y_train)

SVC(probability=True)

Training SVC on training set

In [ ]:
clf.predict_proba(X_test.head(1))

array([[0.00780692, 0.94681543, 0.04537766]])

In [ ]:
scores = cross_val_score(clf, X, y, cv=5)
scores.mean()

0.9666666666666666

The Score Measures the accuracy of the SVM function

# i. Use sklearn to train a Neural Network (MLP Classifier) on the training set

# ii. For a sample datapoint, predict the probabilities for each possible class

# iii. Report on the score for the Neural Network, what does the score measure?

# iv: Experiment with different options for the neural network, report on your best configuration (the highest score I was able to achieve was 0.8666)

In [ ]:
 clf = MLPClassifier(max_iter=700, activation = 'relu').fit(X_train, Y_train)

Training Neural Network (MLP Classifier)

In [ ]:
clf.predict_proba(X_test.head(1))

array([[6.96096792e-04, 9.96606270e-01, 2.69763293e-03]])

In [ ]:
scores = cross_val_score(clf, X, y, cv=5)
scores.mean()

0.9800000000000001

The Score Measures the accuracy of the MLPClassifier function

In [ ]:
clf = MLPClassifier(max_iter=700, activation = 'tanh').fit(X_train, Y_train)
scores = cross_val_score(clf, X, y, cv=5)
scores.mean()

0.9800000000000001

In [ ]:
clf = MLPClassifier(max_iter=1000, activation = 'logistic').fit(X_train, Y_train)
scores = cross_val_score(clf, X, y, cv=5)
scores.mean()

0.9733333333333334

Highest Accuracy I'm getting is approximately 98%, with relu and tanh, the mlp classifiers doesn't change, but with logistic it alterates between 96 and 98 Accuracy %

# i. Use sklearn to 'train' a k-Neighbors Classifier
# Note: KNN is a nonparametric model and technically doesn't require training
# fit will essentially load the data into the model see link below for more information
# https://stats.stackexchange.com/questions/349842/why-do-we-need-to-fit-a-k-nearest-neighbors-classifier

# ii. For a sample datapoint, predict the probabilities for each possible class

# iii. Report on the score for kNN, what does the score measure?

In [ ]:
clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(X,y)

KNeighborsClassifier(n_neighbors=3)

Training KNN model

In [ ]:
clf.predict_proba(X_train.head(1))

array([[0.        , 0.66666667, 0.33333333]])

In [ ]:
scores = cross_val_score(clf, X, y, cv=5)
scores.mean()

0.9666666666666668

The Score Measures the accuracy of the kNN function

# Conclusions and takeaways

I'm still somewhat unsure if my scores are absolutely correct, since they still seem a little high, even with a low cv for cross validation. However they are much better results than when getting the scores from the test sets directly, which always gave me "100%" Accuracy, though I don't understand completely why. The one that gave me the highest accurracy was the neural network, which isn't too suprising considering how many parameters sklearn has for it. I did notice however, that it also took the longest time to get a result out of all the models.